language: rust
rust:
  - nightly
#  - stable

os:
  - linux
#  - osx

addons:
  apt:
    packages:
      - libpcap-dev
#  homebrew:
#    packages:
#      - libpcap

script:
  - cargo test -- --nocapture

cache: cargo

branches:
  only:
    - master

after_success: |
  cargo doc \
  && echo '<meta http-equiv=refresh content=0;url=pcap_sys/index.html>' > target/doc/index.html && \
  sudo pip install ghp-import && \
  ghp-import -n target/doc && \
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
