language: rust
rust:
  - stable
  - nightly

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libpcap-dev
  homebrew:
    packages:
      - libpcap

script:
  - cargo test -- --nocapture

cache: cargo

branches:
  only:
    - master

notifications:
  email:
    on_success: never
