# from https://github.com/starkat99/appveyor-rust

os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - appveyor DownloadFile https://nmap.org/npcap/dist/npcap-sdk-1.01.zip -FileName npcap-sdk-1.01.zip
  - 7z x -onpcap-sdk-1.01 npcap-sdk-1.01.zip
  - set PCAP_LIBDIR=npcap-sdk-1.01\Lib\x64
  - appveyor DownloadFile https://nmap.org/npcap/dist/npcap-0.99-r8.exe -FileName npcap-0.99-r8.exe
  - 7z x -y "npcap-0.99-r8.exe" "$SYSDIR\wpcap.dll" "$SYSDIR\Packet.dll"
  - set PATH=.\$SYSDIR\;%PATH%

test_script:
  - cargo test -- --nocapture

build: false

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false
